CREATE TABLE IF NOT EXISTS ACCOUNT (
  ID INT AUTO_INCREMENT  PRIMARY KEY,
  ACCOUNT_NUMBER VARCHAR(8) NOT NULL,
  CURRENCY VARCHAR(5) NOT NULL,
  BALANCE DECIMAL(20, 2) NOT NULL,
  UNIQUE (ACCOUNT_NUMBER, CURRENCY)
);